// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      // case TargetPlatform.android:
      //   return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDebWtktvtUI',
  //   appId: '1:XXXXXX:ios:*****',
  //   messagingSenderId: '234235576655',
  //   projectId: 'ht-3434d',
  //   storageBucket: 'XXXXX.firebasestorage.app',
  //   iosBundleId: 'com.XXXXX.XXXXX',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN3rB8bv2rFxqYnYuXtUa92IiTaLvINCg',
    appId: '1:723663894847:android:c81f29dd0833641050fb8a',
    messagingSenderId: '723663894847',
    projectId: 'pedometer-android-a3df1',
    storageBucket: 'pedometer-android-a3df1.firebasestorage.app',
    androidClientId: 'com.pedometer.step.counter.walking.tracker',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkUdUaBV6qrHmnwwYSzpZmmDocKwMuewQ',
    appId: '1:619858171550:ios:db9ae3d6e3c5aeabadcd8f',
    messagingSenderId: '619858171550',
    projectId: 'pedometer-ios-72cf7',
    storageBucket: 'pedometer-ios-72cf7.firebasestorage.app',
    iosBundleId: 'com.pedometer.step.counter.walking.tracker',
  );
}

// {
// "project_info": {
// "project_number": "723663894847",
// "project_id": "pedometer-android-a3df1",
// "storage_bucket": "pedometer-android-a3df1.firebasestorage.app"
// },
// "client": [
// {
// "client_info": {
// "mobilesdk_app_id": "1:723663894847:android:c81f29dd0833641050fb8a",
// "android_client_info": {
// "package_name": "com.pedometer.step.counter.walking.tracker"
// }
// },
// "oauth_client": [],
// "api_key": [
// {
// "current_key": "AIzaSyBN3rB8bv2rFxqYnYuXtUa92IiTaLvINCg"
// }
// ],
// "services": {
// "appinvite_service": {
// "other_platform_oauth_client": []
// }
// }
// }
// ],
// "configuration_version": "1"
// }
