// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      // case TargetPlatform.android:
      //   return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDebWtktvtUI',
  //   appId: '1:XXXXXX:ios:*****',
  //   messagingSenderId: '234235576655',
  //   projectId: 'ht-3434d',
  //   storageBucket: 'XXXXX.firebasestorage.app',
  //   iosBundleId: 'com.XXXXX.XXXXX',
  // );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyCohl7jFNg0g3_btLExnBANNVFnjBMpdTk',
  //   appId: '1:125946237732:android:c813c913a30bd53d0ad9b1',
  //   messagingSenderId: '125946237732',
  //   projectId: 'ht-chooser-android',
  //   storageBucket: 'ht-chooser-android.firebasestorage.app',
  //   androidClientId: 'com.mobiunity.XXX',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkUdUaBV6qrHmnwwYSzpZmmDocKwMuewQ',
    appId: '1:619858171550:ios:db9ae3d6e3c5aeabadcd8f',
    messagingSenderId: '619858171550',
    projectId: 'pedometer-ios-72cf7',
    storageBucket: 'pedometer-ios-72cf7.firebasestorage.app',
    iosBundleId: 'com.pedometer.step.counter.walking.tracker',
  );
}
